services:
  vision-api:
    build: .
    ports:
      - "8029:8029"
    environment:
      - APP_MODULE=effnet_api:app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
